import './globals.css';
import { NavBar } from '@/components/layout/navbar/NavBar';
import { Footer } from '@/components/layout/footer/Footer';
import type { Metadata } from 'next';
import { Providers } from './providers';

export const metadata: Metadata = {
    title: 'Leonardo Aranguren',
    description: 'Generated by Leonardo Aranguren',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body>
                <Providers>
                    <NavBar />
                    <main>{children}</main>
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
