import type { Metadata } from 'next';
import './globals.css';
import { NavBar } from '@/components/layout/navbar/NavBar';
import { ThemeRegistry } from '../contexts/ThemeContext';
import { Footer } from '@/components/layout/footer/Footer';

export const metadata: Metadata = {
    title: 'Leonardo Aranguren',
    description: 'Generated by Leonardo Aranguren',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ThemeRegistry>
                    <NavBar />
                    <main>{children}</main>
                    <Footer />
                </ThemeRegistry>
            </body>
        </html>
    );
}
