import './globals.css';
import { Amplify } from 'aws-amplify';
import outputs from '@/amplify_outputs.json';
import type { Metadata } from 'next';

import { NavBar } from '@/components/layout/navbar/NavBar';
import { Footer } from '@/components/layout/footer/Footer';
import { Providers } from './providers';
import { ThemeTransitionEnabler } from '@/components/ThemeTransitionEnabler';

// Configure Amplify on the client side
Amplify.configure(outputs, { ssr: true });

export const metadata: Metadata = {
    title: 'Leonardo Aranguren',
    description: 'Generated by Leonardo Aranguren',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <ThemeTransitionEnabler />
                    <NavBar />
                    <main>{children}</main>
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
