// CI stub — real file is generated by `ampx sandbox` into .amplify/generated/env/
export const env = process.env as unknown as LambdaProvidedEnvVars &
    AmplifyBackendEnvVars;

type LambdaProvidedEnvVars = {
    AWS_REGION: string;
    AWS_ACCESS_KEY_ID: string;
    AWS_SECRET_ACCESS_KEY: string;
    AWS_SESSION_TOKEN: string;
};

type AmplifyBackendEnvVars = {
    FROM_EMAIL_ADDRESS: string;
    CV_BUCKET_NAME: string;
    ADMIN_EMAIL: string;
    RECAPTCHA_SECRET_KEY: string;
    AMPLIFY_DATA_DEFAULT_NAME: string;
};
